services:
  voidbrain-net:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4220:4220'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start -- --host 0.0.0.0 --port 4220 --poll=500 --hmr
    networks:
      - voidbrain-network

networks:
  voidbrain-network:
    driver: bridge
