
services:
  build-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run build -- --configuration=production
    networks:
      - voidbrain-network

  voidbrain-net:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4220:4220'
    volumes:
      - .:/app
      - /app/node_modules
      - ./dist/voidbrain.net:/dist
    environment:
      - NODE_ENV=production
    command: npx express -s /dist/browser/browser -p 4220 -c "res.header('Cache-Control', 'public, max-age=31536000');" -e html
    depends_on:
      - build-app
    networks:
      - voidbrain-network

networks:
  voidbrain-network:
    driver: bridge
