
services:
  build-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install -g @angular/cli@latest && npm install && npm run build -- --configuration=production"
    networks:
      - voidbrain-network

  voidbrain-net:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - '4220:4220'
    environment:
      - NODE_ENV=production
    depends_on:
      - build-app
    networks:
      - voidbrain-network

networks:
  voidbrain-network:
    driver: bridge
